name = "melkchainnn"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[vars]
# Set this to your backend API origin (e.g., https://api.example.com)
API_ORIGIN = ""

[observability]
enabled = true

